### ISSUE TITLE
Old versus New Wallet Coins

### ISSUE THREAD

**Issue by imrecsoka** [Printex-official/printex-core#3]
I have coins i spent my time and dedication to support this networkand i dont know how to get them transferred to the crypto-bridge wallet and then in to the new wallet.
Please can somebody help me, i am hope i am not too late, how can i do this?
![image](https://user-images.githubusercontent.com/25494601/43972539-ff41b9a4-9cd4-11e8-8983-c4fc234c3106.png)
I have tried to start the new wallet with the old wallet_block chain place.

**Comment by Boumbacomputer** [comment]
We have swapped coins and forked chain, wich mean you cannot send your old coins from the old wallet and chain to the new wallet and chain. If you get that error, it is most likely that you are trying to open your old wallet.dat on the new wallet wich is not on the same chain. There was a website during the swap with the whole process to get new coins, but that procedure is now closed. IF (and IF is the important word) you can still swap your coins, only Riggs on our discord will be able to help you with the swap. To join our discord:
https://discord.gg/qaneFPm
