### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [Printex-official/printex-core#5]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository

File in question: 
      printex-core/COPYING

**Comment by Iconoclasta** [comment]
Over 3 weeks have passed and you have not solved this issue. I will be passing this notice to our legal department should you not comply within 24h.

**Comment by printech** [comment]
Hello Iconoclasta.

Sorry we no see your mess before cause we focused on our dev platform part. now is fixed. Thanks you.

**Comment by Iconoclasta** [comment]
Thank you for complying. I am closing this issue.
